### ISSUE TITLE
Can this work with C++ files?

### ISSUE THREAD

**Issue by GaurangTandon** [sharmaeklavya2/croupier#2]
Hey, I'm just curious if croupier can work with C++ files, or any modifications are required for the same.

**Comment by sharmaeklavya2** [comment]
If you have written your programs in C++, you have to compile them first:

```
$ g++ main.cpp -o main.exe
$ g++ judge.cpp -o judge.exe
$ python croupier.py './main.exe' './judge.exe'
```
